Update property-update.yml

diff --git a/.github/workflows/property-update.yml b/.github/workflows/property-update.yml
--- a/.github/workflows/property-update.yml
+++ b/.github/workflows/property-update.yml
@@ -32,10 +32,13 @@ jobs:
           BASE_PATH="${{ github.event.inputs.BASE_PATH }}"
 
           echo "Cloning GitOps repository '$GITOPS_REPO'..."
-          git clone --bare https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/$GITOPS_REPO.git gitops-repo
-          
+          git clone --bare https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/$GITOPS_REPO.git gitops-repo 
           cd gitops-repo
-
+          
+          if [ ! -d "$BASE_PATH" ]; then
+            echo "::error::[ERROR] Release folder does not exist in branch: $RELEASE_BRANCH"
+            exit 1
+          fi
       - name: Fetch & Checkout Release Folder from Release Branch
         run: |
           set -e
